# fly.toml app configuration file generated for phenomena-dev on 2023-07-18T14:23:29-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phenomena-dev"
primary_region = "atl"

